# Web App admin user
# user: admin
# pass: 5TK174F5JeyoxF5U6A0PJo76oL5X7oXW
#

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${VUE_APP_PGPASSWORD}
      POSTGRES_USER: ${VUE_APP_PGUSER}
      POSTGRES_DB: ${VUE_APP_PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/database.sql:/docker-entrypoint-initdb.d/01-database.sql:ro
      - ./db/admin.sql:/docker-entrypoint-initdb.d/02-admin.sql:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080

  backend:
    build: ./api
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      VUE_APP_PGHOST: ${VUE_APP_PGHOST}
      VUE_APP_PGPORT: ${VUE_APP_PGPORT}
      VUE_APP_PGUSER: ${VUE_APP_PGUSER}
      VUE_APP_PGPASSWORD: ${VUE_APP_PGPASSWORD}
      VUE_APP_PGDATABASE: ${VUE_APP_PGDATABASE}
      VUE_APP_WSS_PORT: ${VUE_APP_WSS_PORT}
      VUE_APP_WSS_PING_INTERVAL: ${VUE_APP_WSS_PING_INTERVAL}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      API_PORT: ${API_PORT}
      VOTING_CHAT_FIXED_DURATION: ${VOTING_CHAT_FIXED_DURATION}
      VOTING_CHAT_MAX_EXTRA_TIME: ${VOTING_CHAT_MAX_EXTRA_TIME}
      PROJECT_COUNT: ${PROJECT_COUNT}
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        VUE_APP_WSS_PORT: ${VUE_APP_WSS_PORT}
        API_PORT: ${API_PORT}
        BACKEND_HOST: backend
        VUE_APP_API: ${VUE_APP_API}
        VUE_APP_WSS: ${VUE_APP_WSS}
        VUE_APP_GUEST_HOME: ${VUE_APP_GUEST_HOME}
        VUE_APP_USER_HOME: ${VUE_APP_USER_HOME}
        NGINX_PUBLIC_SERVER_PORT: ${NGINX_PUBLIC_SERVER_PORT}
    ports:
      - "${NGINX_PUBLIC_SERVER_PORT}:80"
    environment:
      VUE_APP_WSS_PORT: ${VUE_APP_WSS_PORT}
      API_PORT: ${API_PORT}
      BACKEND_HOST: backend
    depends_on:
      - db
      - backend

volumes:
  pgdata:


#    ports:
#      - "8080:8080"   # Vue CLI
#      # or "5173:5173" if using Vite
#    volumes:
#      - ./my-app:/app
#      - /app/node_modules   # prevent node_modules from being overwritten
#    environment:
#      VUE_APP_API: ${VUE_APP_API}
#      VUE_APP_WSS: ${VUE_APP_WSS}
#      #VUE_APP_ON_JOIN_GAME="push"
#      VUE_APP_GUEST_HOME: ${VUE_APP_GUEST_HOME}
#      VUE_APP_USER_HOME: ${VUE_APP_USER_HOME}